/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Stub for `convex/_generated/api.ts`.
 *
 * The real file is auto-generated by `npx convex dev`. This stub returns
 * stable, cached function-reference proxies so React hooks (which compare
 * reference identity across renders) don't loop. When you connect Convex
 * for real, this file is overwritten.
 */
function makeRef(path: string) {
  return { _isConvexFunctionRef: true, _path: path } as any;
}

function makeNamespace(path: string): any {
  const cache: Record<string, any> = {};
  return new Proxy(makeRef(path), {
    get(_target, prop: string) {
      if (typeof prop !== 'string') return undefined;
      if (prop === '_isConvexFunctionRef' || prop === '_path') return _target[prop as any];
      if (!(prop in cache)) cache[prop] = makeNamespace(`${path}.${prop}`);
      return cache[prop];
    },
  });
}

export const api: any = makeNamespace('api');
export const internal: any = makeNamespace('internal');
